name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Install deps
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Upload dist artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy Pages
        uses: actions/deploy-pages@v4
